config/routes.rb
Bookmarks1::Application.routes.draw do
  
  resources :books 

  resources :users do  
  get "register", :on => :collection
  get "thanq", :on => :collection
  get "delete",:on => :collection
  get "profile",:on => :collection
  end

  resources :login do
  get "logout", :on => :collection
  end
  

  get "home/index"
  get "home/show"
  get "home/viewall"

   root :to => "home#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
   validates :title, :presence => true
   validates :discription, :presence => true, :length => { :minimum => 5 }
   validates  :url, :presence => true

 
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :books,:dependent => :destroy
   email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :name, :presence => true
   validates :password, :presence => true, :length => { :maximum => 5 }
   validates :email, :presence => true, :format   => { :with => email_regex }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
   @user =User.find(session[:user])
   @books = Book.where(:user_id => @user.id)
   
  end
 def create
   @user =User.find(session[:user])
   @book=Book.new(:title => params[:book][:title],:discription => params[:book][:discription],:url => params[:book][:url],:user_id => @user.id)

        respond_to do |format|
         if @book.save
            format.html { redirect_to users_path }
        else
            format.html{render :action => "new"}
      
       end
    end
 end
 def new
 @book = Book.new
 end
 def show
  @book = Book.find(params[:id])
 end
 def edit
  @book = Book.find(params[:id])
 end
 def update
 puts"$$$$$$$$$$$$$$$$$$$$$$$$$",params
 @book = Book.find(params[:id])
 respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(users_path, :notice => 'Update was successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
 end
 def destroy
    @book= Book.find(params[:id])
    @book.destroy
   redirect_to users_path
 end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users=User.limit(3).order("created_at DESC")
    @books=Book.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end
  def viewall
     @users=User.all 
  end
 def show
  @user =User.find(params[:id])
  @books=Book.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
 end


end

app/controllers/login_controller.rb
class LoginController < ApplicationController
 def index
   @user = User.all
  end
  def create
   @user = User.new(params[:user])
   @usr = User.find_all_by_email(@user.email)
   if(!@usr.blank? && @usr.first.password.eql?(@user.password))
    session[:user] = @usr.first.id
    flash[:notice] = "Logged in Successfully"

    redirect_to users_path
   else
    flash[:error] = "Enter Proper Email And Password"
    redirect_to home_index_path
   end
  end
 def logout
  session[:user] = nil if session[:user]
   redirect_to home_index_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @user =User.find(session[:user])
     @books = Book.where(:user_id => @user.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
     
     
  end

  def show
   @book = Book.find(params[:id])
  end

  def edit
  @user = User.find(params[:id])
  end

  def new
  @book = Book.new
  end
  def create
   if (params[:user][:password] == params[:confirmpassword])

        @user=User.new(:name => params[:user][:name],:email => params[:user][:email],:password => params[:user][:password])

        respond_to do |format|
         if @user.save
            format.html { redirect_to thanq_users_path }
            
        else
            format.html{render :action => "register"}
      
       end
    end
   else
       redirect_to register_users_path, :notice =>'*password should match'
  end
 
  end
def update
  puts "sssssssSSSSS"
   @user = User.find(params[:id])
   puts "rrrrrrrrrrrrrrr"
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'Your changes are succesfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
  end
def destroy
    puts "hhh"
   @user = User.find(params[:id])   
   @user.destroy
   redirect_to delete_users_path
  end
 def register
 @user=User.new 
 end
 def delete
 end
 def profile
  @user =User.find(session[:user])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<div align="left"><%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> title cannot be blank we need to enter bookmarks:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>
<%= f.label :Title %></br>
<%= f.text_field :title %></br>
<%= f.label :Discription %></br>
<%= f.text_field :discription %></br>
<%= f.label :Url %></br>
<%= f.text_field :url %></br></br>
<%= f.submit "submit" %>
<%end %>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', users_path %>

app/views/books/index.html.erb
<div style="color:grey"><h1><i>All My BookMarks</i></h1></div></br>

<table >
 

<% @books.each do |book| %>
  <tr>
    <td><span>Title:</span></td>
    <td><%= link_to book.title, book.url ,:target =>:_blank %></td></tr>
   <td><span>Description:</span></td>
    <td><%= link_to book.discription %></td></tr>
   
    <td><%= link_to 'Show', book %>
    <%= link_to 'Edit', edit_book_path(book) %>
    	<%= link_to 'Destroy', book, :confirm => 'Are you sure?', :method => :delete %></td></tr>
  


<% end %>
</table>

<br />

<br />

<%= link_to 'New Books', new_book_path %>
<%= link_to "home page",users_path %>

app/views/books/new.html.erb
<div align="left" style="color:maroon"><i style="font-size:20px">Enter New BookMark </i></div></br></br>
<div s><%= render 'form' %></div>

app/views/books/show.html.erb
<b>Title : </b>
 <%= @book.title %></br>
<b>Discription : </b>
<%= @book.discription %></br>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', users_path %>

app/views/home/_form.html.erb
<div align="center"><%= form_for(:user,:url => {:controller => "login", :action => "create"}) do |f|%>

<i style="color:green">Already A User  :</i>    
<%= f.label :email %>
  <%= f.text_field :email, :value => "" %>
<%= f.label :Password  %>
  <%= f.password_field :password, :value => "" %>
  <%= f.submit "Login" %><br /></br />
<% end %></div>

app/views/home/index.html.erb
<%= render 'form' %>

<div align="right">
 <i style="font-size:20px">Do u Want To Register</i>

 <%= link_to "Register Now", register_users_path %>
 
</div></br></br>
<div id='body'>
  <div id='body-left' align="left">
  <i style="font-size:30px">Latest BookMarks</i></br>
<% @books.each do |books| %>
<span>Title :</span><%= link_to books.title,books.url , :target=>:_blank %><br>
<span>Discription :</span><%=  books.discription %><br>

<% end %>
<%= will_paginate @books %>
  </div>
  <div id='body-right' align="right">
<i style="font-size:30px">Users BookMarks</i></br>
<% @users.each do |user| %>
<span>Name  :<span><%= link_to user.name , home_show_path(:id => user.id) %></br>
<div>TotalBookMarks :	 <%= user.books.count  %></div>
<%end %>
<%= form_tag("viewall", :method => :get) %>
<%= submit_tag "viewall" %>
</div>
  
</div> 

app/views/home/show.html.erb
<b>Name : </b>
<%= @user.name %><br />
<b>Email : </b>
<%= @user.email %><br />
<% @user.books.each do |b| %>
<span><b>Book:</b></span>
<%= link_to b.title,b.url %></br>
<span><b>Discription:</b></span>
<%=  b.discription %></br>
<% end %></br></br>
<%= link_to 'Back', home_index_path %>

app/views/home/viewall.html.erb
<% @users.each do |user| %>
<span>Name</span><%= link_to user.name, home_show_path(:id => user.id) %></br>
<div>TotalBookMarks :	 <%= user.books.count  %></div>
<% end %>
</br>
<div><i><%= link_to "back to home page",home_index_path %></i></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body bgcolor="#F7F7F0">
<% flash.each do |key, msg| %>
    <%=content_tag :div, msg, :id =>"flash_#{key}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<%= render 'home/form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> title cannot be blank we need to enter bookmarks:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %> </br>
  <%= f.label :email %>
  <%= f.text_field :email %> </br>
  <%= f.label :password %>
  <%= f.password_field :password %> </br>
  confirmpassword
  <%= password_field_tag :confirmpassword %> 
  <%= f.submit "submit"%> </br>
<% end %>

app/views/users/delete.html.erb
<div align="cnter" style="color:red"><i style="font-size:30">You are Permantly Deleted From Our site</i><div></br>
<div style="color:red"><i style="font-size:15px"><%= link_to "Back to HomePage",home_index_path %></i></div>

app/views/users/edit.html.erb
<%= render 'form' %>


<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div style="color:green"><h1> HI <i><%= @user.name %></i></h1></div>
<div align="center"> <%= @user.email %></div>
<div align="right" >
<span ><%= link_to "My Profile", profile_users_path %></span>
<span ><%= link_to "logout",logout_login_index_path %></span>
</div></br></br></br>
<div id='body'>
  <div id='body-left' align="left">
<b>Name :</b>
<%= @user.name %></br>
<i>Total Bookmarks : </i>
<%= link_to @user.books.count,books_path %></br>

<%= link_to "edit", edit_user_path(@user.id) %>
<%= link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete %></br></br>
<div style="color:maroon"><i style="font-size:20px"><u>My Bookmarks</u></i></div></br>
<% @books.each do |books| %>
  <tr>
    <td><span>Title :</span></td>
    <td><%= link_to books.title,books.url ,:target=>:_blank%></td></tr></br>    
    <td><span>Discription :</span></td>
    <td><%=  books.discription %></td></tr></br>

<tr>
    <td><%= link_to 'Show', books %></td>
    <td><%= link_to 'Edit', edit_book_path(books) %></td>
    <td><%= link_to 'Destroy', books, :confirm => 'Are you sure?', :method => :delete %></td></tr></br></br></br>
  </tr>
<% end %>
</table></br>
<%= will_paginate @books %>



</div>
<div id='body-right' align="right">
  <div style="color:lightblue"><i style="font-size:20px">Add A New Book Mark</i></div></br></br>
   <div ><%= form_for(:book,:url => {:controller => "books", :action => "create"}) do |f| %>   
   <%= f.label :Title %>
  <%= f.text_field :title %></br>
  <%= f.label :Discription %>
  <%= f.text_field :discription %></br>
  <%= f.label :Url %>
  <%= f.text_field :url %></br></br>
  <%= f.submit "submit" %>
<%end %>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/profile.html.erb
<h2><i>My Profile</i></h2>
<b>Name :</b>
<%= @user.name %></br>
<b>Email :</b>
<%= @user.email %></br>
<i>Total Bookmarks : </i>
<%= link_to @user.books.count,books_path %></br>

<%= link_to "edit", edit_user_path(@user.id) %>
<%= link_to "Back",users_path %>

app/views/users/register.html.erb
<div align="center" style="color:green"><i style="font-size:30px">Register With Us to Share Your BookMarks With All</i></div>
<div align="center"><%= form_for(:user,:url => {:controller => "users", :action => "create"}) do |f|%>
 <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> title cannot be blank we need to enter bookmarks:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %> </br>
  <%= f.label :email %>
  <%= f.text_field :email %> </br>
  <%= f.label :password %>
  <%= f.password_field :password %> </br>
  <%= f.label :confirmpassword %>
  <%= password_field_tag :confirmpassword %></br>
  <%= f.submit %> </br>

<% end %><div>

app/views/users/show.html.erb
<b>Content : </b>
 <%= @user.name %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/thanq.html.erb
<div align ="center" style="color:red"><i style="font-size:30px">Thank you for Registration With Us </i><div>
<i align="right"><%= link_to "enjoy by  sharing your bookmarks", home_index_path %><i></br>
</br></br>
<div align="right"><i>Sign in  Now<i></div>
<div align="right" style="color:blue"><%= form_for(:user,:url => {:controller => "login", :action => "create"}) do |f|%>
 
<%= f.label :email %>
  <%= f.text_field :email, :value => "" %></br>
<%= f.label :Password  %>
  <%= f.password_field :password, :value => "" %></br>
  <%= f.submit "Login" %><br /></br />
<% end %></div>